version: '3.4'

services:
  webapp:
    image: web:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - db-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - db-network

networks:
  db-network: