version: '3.4'

services:
  webapp:
    image: web-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - db-connect
  db:
    image: postgres
    restart: always
    networks:
      - db-connect

networks:
  db-connect: